FROM php:7.2.5-apache

MAINTAINER egidio docile

RUN apt-get update 

RUN curl -sS https://getcomposer.org/installer | php

RUN mv composer.phar /usr/local/bin/composer

RUN chmod +x /usr/local/bin/composer

RUN composer self-update

RUN apt-get install -y zlib1g-dev

RUN docker-php-ext-install zip

RUN apt-get install -y openssl


RUN a2enmod rewrite

RUN service apache2 restart
